Fixed: - Removed unecessary if-else conditions - Downloading the db file on every run (check for older than 1 day had no effect) - Quoting of some vars - no quiet option for mplayer when called with proxy Added: - Parameter for excluding a word from random playing - Better display of the song played (if possible)

diff --git a/radio b/radio
--- a/radio
+++ b/radio
@@ -32,14 +32,10 @@ function restorehistory() {
 	"$sqlite" "$db" < "${path}/restore_commands"
 }
 
-if [[ "$1" == "-x" ]];then
-	 if [ -z "$2" ]; then
-		echo "please pass proxy URL after argument -x"
-		exit 1
- 	else
-		proxy="$2"
-		set -- $3 $4 $5
-	fi
+if [[ "$1" == "-x" ]]; then
+	[ -z "$2" ] && die "please pass proxy URL after argument -x"
+	proxy="$2"
+	set -- "$3" "$4" "$5" #read: set params 3 - 5 as params 1 - 3
 fi
 
 get_url='select url from stations where name like "%'
@@ -76,6 +72,11 @@ get_names_with_id+='%"'
 
 get_random='select url from stations order by random() limit 1'
 
+get_random_except='select url from stations where name not like "%'
+get_random_except+="$3"
+get_random_except+='%"'
+get_random_except+='order by random() limit 1'
+
 get_random_for_tag='select url from stations where tags like "%'
 get_random_for_tag+="$2"
 get_random_for_tag+='%"'
@@ -103,6 +104,8 @@ get_all_location='select distinct location from stations'
 
 today=$(date +%s)
 
+[[ ! -d "$path" ]] && die "path $path does not exist"
+
 if [ -f "${path}/db.md5" ]; then
 	md5date=$(date +%s -r "${path}/db.md5")
 	datediff=$((today-md5date))
@@ -122,9 +125,8 @@ if [ -f "${path}/db.md5" ]; then
 			restorehistory
 			rm backup.csv
 			echo "new stations added"
-			mv /tmp/db.md5 "${path}/db.md5"
 		fi
-		rm -f /tmp/db.md5
+		mv /tmp/db.md5 "${path}/db.md5"
 	fi
 else
 	echo "Missing file. Downloading..."
@@ -141,6 +143,10 @@ fi
 case $1 in
 	random)
 		url=$("$sqlite" "$db" "$get_random")
+		if [[ "$2" == "-X" ]]; then
+			[ -z "$3" ] && die "Pass a word you want to search for"
+			url=$("$sqlite" "$db" "$get_random_except")	
+		fi
 		;;
 	-la|--list-all)
 		printStations "$get_stations"
@@ -184,19 +190,18 @@ case $1 in
 		exec "$sqlite" "$db" "$get_most_played"
 	;;
 	-u|--update)
-		location=$(which $0)
+		location="$(which "$0")"
 		[[ "$location" == "" ]] && die "Location of Script could not be identified, please include it in your PATH variable"
 		echo "Updating radio Script at $location... "
 		echo
 		cd /tmp/ || die "can't cd to /tmp"
 		wget -q https://raw.githubusercontent.com/todestoast/radio/master/radio
-		mv radio $location
-		if [ $? -ne 0 ]; then
+		mv radio "$location" || {
 			echo  "Unable to move updated version of the script to $location. Retrying with sudo..."
 			echo
-			sudo mv radio $location || die "Unable to move updated version of the script to $location. You can find it at /tmp/radio"
-			sudo chmod a+x $location
-		fi
+			sudo mv radio "$location" || die "Unable to move updated version of the script to $location. You can find it at /tmp/radio"
+			sudo chmod a+x "$location"
+		}
 		echo "Script sucessfully updated"
 		exit 0
 	;;
@@ -284,24 +289,22 @@ if [ ${#url}  -eq 0 ]; then
 fi
 
 #if string contains newlines therefore multiple urls
-if [ $(echo "$url" | wc -l) -gt 1 ]; then
+if [ "$( wc -l <<<"$url" )" -gt 1 ]; then
 	#select names
-	#echo $get_names_with_id
 	printStations "$get_names_with_id"
 	exit 1;
-else
-	get_name_for_url='select name from stations where url="'
-	get_name_for_url+="$url"
-	get_name_for_url+='"'
-	name="$("$sqlite" "$db" "$get_name_for_url")"
-	echo "Playing $name"
-	echo
-	if [ -z $proxy ]; then
-		 mplayer -quiet "$url" 2>&1 | sed -nu '/^ICY/ p' | sed 's/StreamUrl\=.*\;//'
-	else
-		mplayer "${proxy}/$url" | sed -nu '/^ICY/ p' | sed 's/StreamUrl\=.*\;//'
-	fi
 fi
+
+get_name_for_url='select name from stations where url="'
+get_name_for_url+="$url"
+get_name_for_url+='"'
+name="$("$sqlite" "$db" "$get_name_for_url")"
+echo "Playing $name"
+echo
+
+[ -z "$proxy" ] || url="${proxy}/$url"
+mplayer -quiet "$url" 2>&1 | sed -nu "s/^ICY.*StreamTitle='\([^;]*\)';.*/\1/p"
+
 end=$(date +%s)
 playtime=$(((end-today)/60))
 set_history='insert into history values('
