update process optimized for missing rights and documented

diff --git a/radio b/radio
--- a/radio
+++ b/radio
@@ -188,7 +188,11 @@ case $1 in
 		echo "Updating radio Script at $location... "
 		cd /tmp/ || die "can't cd to /tmp"
 		wget -q https://raw.githubusercontent.com/todestoast/radio/master/radio
-		mv radio $location || die "Unable to move updated version of the script to $location. You can find it at /tmp/"
+		mv radio $location
+		if [ $? -ne 0 ]; then
+			echo  "Unable to move updated version of the script to $location. Retrying with sudo..."
+			sudo mv radio $location || die "Unable to move updated version of the script to $location. You can find it at /tmp/radio"
+		fi
 		exit 0
 	;;
 		#make -p also work with the ID and the backup stream
